### ISSUE TITLE
Feature Request: Please publish the extension

### ISSUE THREAD

**Issue by Taytay** [fastai/nbdev-vscode#13]
First, thanks for this! This extension has already been helpful to me and lends legitimacy to nbdev, and using nbdev with VSCode. In fact, I created a [starter-project nbdev template](https://github.com/ynab/nbdev_vscode_template) that installs this extension. Of course it installs this extension using wget, and I need to keep it updated as the vsix gets updated. I'd rather just mark this  as a recommended extension and let everything else take care of itself. 

Would a pull request help out here?
https://code.visualstudio.com/api/working-with-extensions/publishing-extension

**Comment by hamelsmu** [comment]
I can do it :)  After you confirm that the auto-complete works for you on the other issue, I feel like I have enough features to publish.  LMK!

**Comment by hamelsmu** [comment]
Published https://marketplace.visualstudio.com/items?itemName=hamelhusain.nbdev

Looks like I can run the commands
 
- `vsce package` to build the extension file
- `vsce publish` to publish (this also packages things)
