### ISSUE TITLE
Not seeing the auto-complete suggestions for `#|`

### ISSUE THREAD

**Issue by Taytay** [fastai/nbdev-vscode#15]
I haven't had a chance to debug yet, but I'm not seeing those slick new autocomplete suggestions when I type `#|` in a cell. Reporting here in case others see the same.

**Comment by hamelsmu** [comment]
@Taytay It needs to be `#| ` with a trailing space.  I wasn't able for figure out (oddly) how to make it happen without a trailing space.  Does that work for you?

**Comment by Taytay** [comment]
Works like a champ with the new "official" extension published! Thanks!
