### ISSUE TITLE
`vscode:(version 1.74.3)` not supported: Cannot install `nbdev` extension on `VSCode`

### ISSUE THREAD

**Issue by imflash217** [fastai/nbdev-vscode#19]
Getting this message while installing on VSCode-`1.74.3`
```
Can't install 'hamelhusain.nbdev' extension because it is not compatible with the current version of Visual Studio Code (version 1.74.3).
```
<img width="1325" alt="स्क्रीनशॉट २०२३-०४-०४, १६ २५ ३४ पर" src="https://user-images.githubusercontent.com/12234745/229912216-1d77ac48-bf1e-46d9-a340-ac2b0cd46a15.png">

**Comment by binarycache** [comment]
Same issue, can't install for VS Code 1.75.1 too.

**Comment by roy9495** [comment]
It's solved . I installed it for my vs code version : 1.77.3

![Capturevs](https://user-images.githubusercontent.com/98920199/233299751-e551b83b-785b-415a-a358-2014d70f0e3d.JPG)
