### ISSUE TITLE
Add recommended Python extensions to `extensionDependencies`

### ISSUE THREAD

**Issue by seeM** [fastai/nbdev-vscode#22]
Should we? For instance:

- Python extension (`ms-python.python`)
- PyLance. I think this might be installed via the Python extension
- Quarto (`quarto.quarto`)

**Comment by hamelsmu** [comment]
Looks like pylance is include in `ms-python.python` https://github.com/microsoft/vscode-python/blob/main/gulpfile.js#L85

**Comment by hamelsmu** [comment]
I couldn't figure out how to make a "recommened extension" happen in an extension.  I could find how to do it in a workspace but not through extension installation, I was however able to figure out how to bundle several extensions together as an extension pack, which I deployed to the marketplace

![image](https://user-images.githubusercontent.com/1483922/234362793-a7212f76-98c8-4cb4-9dbe-24f491492100.png)
