### ISSUE TITLE
tests require Jupyter extension to be installed

### ISSUE THREAD

**Issue by peterj** [fastai/nbdev-vscode#3]
Note that when running tests, you need to install the Jupyter extension in the test VSCode instance. I've done it manually, however, I bet there has to be a way to automatically install that extension as a dependency.

**Comment by rebornix** [comment]
This can be archived by adding `ms-toolsai.jupyter` to `extensionDependencies` in `package.json`.

**Comment by seeM** [comment]
Closing, seems to be solved in `main`:

https://github.com/fastai/nbdev-vscode/blob/4da09a4d985eea47c9dca904da0e1d1defd390c4/package.json#L12-L14
